#!/bin/bash/

#VARIABLES
	       red='\033[1;31m'
                green='\033[1;32m'
                yellow='\033[1;33m'
                blue='\033[1;34m'
                magenta='\033[1;35m'
                cyan='\033[1;36m'
                reset='\033[0m'

cp  packtools2.0 /data/data/com.termux/files/usr/bin		
printf $cyan
echo "INSTALANDO REPOSITORIOS"
printf $reset
apt update && apt upgrade -y
apt install git -y
apt install python -y
apt install python2 -y
apt install util-linux -y
apt install openssh -y
apt install php -y
apt install figlet -y
printf $green
figlet -f smslant finalizado
printf $reset



